---
# Variables for tls-cert-monitor role

# Architecture mapping for GitHub release assets
arch_map:
  x86_64: amd64
  aarch64: arm64
  armv7l: arm
  i386: 386
  i686: 386
  AMD64: amd64  # Windows architecture name

# Platform mapping for GitHub release assets
platform_map:
  Linux: linux
  Windows: windows
  Darwin: darwin

# Platform-specific service commands
service_manager:
  Linux: systemd
  Darwin: launchd
  Windows: native