---
# Handlers for tls-cert-monitor role

- name: reload systemd
  systemd:
    daemon_reload: yes
  when: ansible_system == "Linux"

- name: restart tls-cert-monitor
  systemd:
    name: "{{ service_name }}"
    state: restarted
  when: ansible_system == "Linux"

# macOS LaunchDaemon handlers
- name: reload launchd
  shell: launchctl load /Library/LaunchDaemons/com.tlscertmonitor.service.plist
  become: yes
  when: ansible_system == "Darwin"

- name: restart tls-cert-monitor-macos
  shell: |
    launchctl unload /Library/LaunchDaemons/com.tlscertmonitor.service.plist 2>/dev/null || true
    launchctl load /Library/LaunchDaemons/com.tlscertmonitor.service.plist
    launchctl start com.tlscertmonitor.service
  become: yes
  when: ansible_system == "Darwin"

# Native Windows service handlers (v1.2.0+)
- name: restart tls-cert-monitor-windows-native
  win_shell: |
    $serviceName = "{{ service_name }}"

    # Get current service status
    $service = Get-Service -Name $serviceName -ErrorAction SilentlyContinue

    if ($service) {
        Write-Host "Stopping service..."
        Stop-Service -Name $serviceName -Force -ErrorAction SilentlyContinue
        Start-Sleep -Seconds 2

        Write-Host "Starting service..."
        Start-Service -Name $serviceName -ErrorAction Stop
        Start-Sleep -Seconds 2

        # Verify service is running
        $service = Get-Service -Name $serviceName -ErrorAction SilentlyContinue
        if ($service.Status -ne 'Running') {
            throw "Service failed to restart. Status: $($service.Status)"
        }

        Write-Host "Service restarted successfully"
    } else {
        Write-Warning "Service '$serviceName' not found"
    }
  args:
    executable: powershell
  when: ansible_os_family == "Windows"

