services:
  tls-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3200:3200"
    volumes:
      - ./docker/docker.config.yaml:/app/config.yaml:ro
      - ./docker/logs:/app/logs:rw
      - ./docker/cache:/app/cache:rw
      # Mount certificate directories for monitoring
      - ./tests/fixtures/certs:/app/certs
    environment:
      - TLS_MONITOR_LOG_LEVEL=INFO
      - TLS_MONITOR_HOT_RELOAD=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--method=GET", "-O", "/dev/null", "http://localhost:3200/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    profiles:
      - monitoring

  # Optional: Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
    profiles:
      - monitoring

volumes:
  grafana-storage:

networks:
  default:
    name: tls-monitor-network