---
# Ansible inventory for TLS Certificate Monitor deployment
# Copy this to your inventory directory and customize for your environment

all:
  children:
    linux_servers:
      hosts:
        # Example Linux host with SSH key authentication
        webserver01:
          ansible_host: 192.168.1.10
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          cert_dirs_linux:
            - /etc/ssl/certs
            - /etc/nginx/ssl
            - /opt/certificates

        # Example Linux host with password authentication
        appserver01:
          ansible_host: 192.168.1.11
          ansible_user: deploy
          ansible_password: "{{ vault_linux_password }}"
          ansible_become_password: "{{ vault_sudo_password }}"
          cert_dirs_linux:
            - /etc/pki/tls/certs
            - /home/app/certificates

        # Example Linux host with custom SSH port and different user
        dbserver01:
          ansible_host: 192.168.1.12
          ansible_port: 2222
          ansible_user: admin
          ansible_ssh_private_key_file: ~/.ssh/db_key
          ansible_become_user: root

    windows_servers:
      hosts:
        # Example Windows host with SSH key authentication
        winserver01:
          ansible_host: 192.168.1.30
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/windows_key
          cert_dirs_windows:
            - C:\inetpub\ssl
            - C:\certificates

        # Example Windows host with password authentication
        winserver02:
          ansible_host: 192.168.1.31
          ansible_user: Administrator
          ansible_password: "{{ vault_windows_password }}"
          cert_dirs_windows:
            - C:\Program Files\MyApp\certificates

        # Example Windows host using WinRM instead of SSH
        winserver03:
          ansible_host: 192.168.1.32
          ansible_user: ansible
          ansible_password: "{{ vault_windows_password }}"
          ansible_connection: winrm
          ansible_winrm_transport: ntlm
          ansible_winrm_server_cert_validation: ignore
          ansible_port: 5986

  vars:
    # Global variables for all hosts
    service_port: 9090
    scan_interval_seconds: 3600  # 1 hour
    log_level: "INFO"

    # SSH connection timeouts
    ansible_ssh_timeout: 30
    ansible_connect_timeout: 30