blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability
    url: https://github.com/brandonhon/tls-cert-monitor/security/advisories/new
    about: Please report security vulnerabilities through GitHub Security Advisories
  - name: Discussions
    url: https://github.com/brandonhon/tls-cert-monitor/discussions
    about: Ask questions and discuss ideas with the community