{
 "title": "SSL Certificate Health & Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "${host} TLS Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Parsed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "targets": [
    { "expr": "ssl_certs_parsed_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Parse Errors Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "targets": [
    { "expr": "ssl_cert_parse_errors_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Weak Algorithm Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "sum(ssl_cert_deprecated_sigalg_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Weak Key Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 1 },
   "targets": [
    { "expr": "sum(ssl_cert_weak_key_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Duplicate Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "targets": [
    { "expr": "ssl_cert_duplicate_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "8 certificates closest to expiring",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "-topk(\r\n  8,\r\n  -((ssl_cert_expiration_timestamp - time()) / 86400)\r\n)",
     "legendFormat": "{{common_name}}"
    }
   ]
  },
  {
   "title": "SAN Count",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\r\n    ssl_cert_san_count > 0,\r\n    \"common_name\", \"$1\",\r\n    \"path\",\r\n    \"^/etc/nginx/ssl/(.*)\"\r\n)",
     "legendFormat": "{{filename}}"
    }
   ]
  },
  {
   "title": "Duplicate Certs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    { "expr": "ssl_cert_duplicate_names_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Certificate Issuer",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "label_replace(\r\n  ssl_cert_issuer_code == 30, \"issuer_name\", \"DigiCert\", \"file_name\", \".*\"\r\n)\r\nor\r\nlabel_replace(\r\n  ssl_cert_issuer_code == 31, \"issuer_name\", \"Amazon\", \"file_name\", \".*\"\r\n)\r\nor\r\nlabel_replace(\r\n  ssl_cert_issuer_code == 32, \"issuer_name\", \"Other\", \"file_name\", \".*\"\r\n)\r\nor\r\nlabel_replace(\r\n  ssl_cert_issuer_code == 33, \"issuer_name\", \"Self-signed\", \"file_name\", \".*\"\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Across Instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Duplicate Certificates Across Instances",
   "type": "table",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "ssl_cert_expiration_timestamp * on(serial) group_left() (\r\n    count by (serial) (\r\n      count by (serial, instance) (\r\n        ssl_cert_expiration_timestamp\r\n      )\r\n    ) > 1\r\n  )",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}