---
# Group variables for Linux servers
# Configuration format matching config.example.yaml

# SSH connection defaults for Linux hosts
# These can be overridden per host in inventory
ansible_user: "{{ lookup('env', 'USER') }}"  # Use current user by default
ansible_ssh_private_key_file: "~/.ssh/id_rsa"
ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
ansible_become: true
ansible_become_method: sudo

# TLS Certificate Monitor Configuration matching config.example.yaml format
tls_cert_monitor_config:
  # Server settings
  port: 3200
  bind_address: "0.0.0.0"

  # Certificate monitoring
  certificate_directories:
    - "/etc/ssl/certs"
    - "/etc/pki/tls/certs"
    - "/usr/local/share/ca-certificates"
    - "/opt/certificates"

  # Directories to exclude from scanning (optional)
  exclude_directories:
    - "/etc/ssl/certs/private"
    - "/etc/ssl/certs/backup"
    - "/etc/pki/tls/certs/archived"

  # File patterns to exclude from scanning (optional)
  exclude_file_patterns:
    - "dhparam.pem"        # Exclude Diffie-Hellman parameter files
    - ".*\\.key$"         # Exclude private key files
    - ".*backup.*"        # Exclude backup files

  # P12/PFX certificate passwords
  p12_passwords:
    - ""                    # Empty password (no password)
    - "changeit"           # Java keystore default
    - "password"           # Common default
    - "123456"             # Common weak password

  # Scan interval (how often to scan for certificates)
  scan_interval: "5m"

  # Performance settings
  workers: 4

  # Logging
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_file: "/var/log/tls-cert-monitor/tls-monitor.log"

  # Operation modes
  dry_run: false
  hot_reload: true

  # Cache settings
  cache_type: "memory"       # "memory", "file", or "both"
  cache_dir: "/var/cache/tls-cert-monitor"
  cache_ttl: "1h"
  cache_max_size: 10485760   # 10MB (memory)

  # # Security settings
  # enable_ip_whitelist: true
  # allowed_ips:
  #   - "127.0.0.1"           # Localhost IPv4
  #   - "::1"                 # Localhost IPv6
  #   - "192.168.1.0/24"      # Local network (CIDR notation)
  #   - "10.0.0.0/8"
  #   - "192.168.57.0/24"

enable_ip_whitelist: true
allowed_ips:
  - "127.0.0.1"
  - "::1"
  - "10.0.0.0/8"
  - "192.168.57.0/24"

# Service settings
service_user_linux: "tls-monitor"
config_dir_linux: "/etc/tls-cert-monitor"
log_dir_linux: "/var/log/tls-cert-monitor"
bin_dir_linux: "/usr/local/bin"