---
# Group variables for Linux servers

# SSH connection defaults for Linux hosts
# These can be overridden per host in inventory
ansible_user: "{{ lookup('env', 'USER') }}"  # Use current user by default
ansible_ssh_private_key_file: "~/.ssh/id_rsa"
ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
ansible_become: true
ansible_become_method: sudo

# Default certificate directories for Linux
cert_dirs_linux:
  - /etc/ssl/certs
  - /etc/pki/tls/certs
  - /usr/local/share/ca-certificates
  - /opt/certificates

# Linux-specific service settings
service_user_linux: "tls-monitor"
log_dir_linux: "/var/log/tls-cert-monitor"

# Scan configuration optimized for Linux
scan_workers: 4
enable_cache: true
cache_ttl_seconds: 3600

# Linux-specific alert settings
alerts:
  expiry_warning_days: 30
  expiry_critical_days: 7
  weak_key_bits: 2048