# TLS Certificate Monitor Configuration

# Server settings
port: 3200
bind_address: "0.0.0.0"

# TLS settings for metrics endpoint (optional)
# tls_cert: "/path/to/server.crt"
# tls_key: "/path/to/server.key"

# Certificate monitoring
certificate_directories:
  - "/app/certs"
  # Add more directories as needed

# Directories to exclude from scanning (optional)
# These paths will be skipped even if they are within certificate_directories
exclude_directories:
  - "/app/certs/old"
  - "/app/certs/new"
  - "/app/certs/working"
  - "/app/certs/.git"
  - "/app/certs/exclude"
  # Add any subdirectories you want to exclude

# File patterns to exclude from scanning (optional)
# These are regex patterns that will exclude files by name
exclude_file_patterns:
  - "dhparam.pem"        # Exclude Diffie-Hellman parameter files
  - ".*\\.key$"         # Exclude private key files
  - ".*backup.*"        # Exclude backup files
  # Add regex patterns for files you want to exclude

# P12/PFX certificate passwords
# List of passwords to try when decrypting P12/PFX certificate files
# Common passwords are included by default, add your specific ones here
p12_passwords:
  - ""                    # Empty password (no password)
  - "changeit"           # Java keystore default
  - "password"           # Common default
  - "123456"             # Common weak password
  # Add your organization-specific P12 passwords here
  # - "your-p12-password"
  # - "another-password"

# Scan interval (how often to scan for certificates)
scan_interval: "5m"

# Performance settings
workers: 4

# Logging
log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
# log_file: "/var/log/tls-monitor.log"  # If not set, logs to stdout

# Operation modes
dry_run: false
hot_reload: true

# Cache settings
cache_type: "memory"       # "memory", "file", or "both"
cache_dir: "/app/cache"    # Only used when cache_type is "file" or "both"
cache_ttl: "1h"
cache_max_size: 10485760  # 10MB (memory), use 31457280 for file cache (30MB)