---
# Windows installation tasks

- name: Create required directories
  win_file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ install_dir_windows }}"
    - "{{ config_dir_windows }}"
    - "{{ config_dir_windows }}\\certificates"
    - "{{ log_dir_windows }}"

- name: Download Windows binary
  win_get_url:
    url: "https://github.com/{{ github_repo }}/releases/download/{{ release_version }}/{{ platform_name }}-{{ arch_name }}.tar.gz"
    dest: "{{ install_dir_windows }}\\tls-cert-monitor-{{ release_version }}.tar.gz"
    validate_certs: no
  tags:
    - download

- name: Extract Windows binary
  win_shell: |
    $tarPath = "{{ install_dir_windows }}\\tls-cert-monitor-{{ release_version }}.tar.gz"
    $extractPath = "{{ install_dir_windows }}"

    # Extract tar.gz
    tar -xzf $tarPath -C $extractPath

    # Verify executable exists
    if (-not (Test-Path "$extractPath\\tls-cert-monitor.exe")) {
        throw "Failed to extract tls-cert-monitor.exe"
    }

    # Remove archive
    Remove-Item $tarPath -Force
  args:
    executable: powershell

- name: Deploy configuration file
  win_template:
    src: config-windows.yaml.j2
    dest: "{{ config_dir_windows }}\\config.yaml"
    backup: yes

# Native Windows Service Installation (v1.2.0+)
- name: Install Windows service (native method)
  win_shell: |
    $exePath = "{{ install_dir_windows }}\\tls-cert-monitor.exe"
    $configPath = "{{ config_dir_windows }}\\config.yaml"

    # Check if service exists
    $service = Get-Service -Name "{{ service_name }}" -ErrorAction SilentlyContinue

    if ($service) {
        Write-Host "Stopping existing service..."
        Stop-Service -Name "{{ service_name }}" -Force -ErrorAction SilentlyContinue
        Start-Sleep -Seconds 2

        Write-Host "Uninstalling existing service..."
        & $exePath --service-uninstall
        Start-Sleep -Seconds 2
    }

    # Install the service with auto-start
    Write-Host "Installing native Windows service..."
    & $exePath --service-install --config $configPath

    if ($LASTEXITCODE -ne 0) {
        throw "Failed to install Windows service. Exit code: $LASTEXITCODE"
    }

    # Start the service
    Write-Host "Starting Windows service..."
    & $exePath --service-start

    if ($LASTEXITCODE -ne 0) {
        throw "Failed to start Windows service. Exit code: $LASTEXITCODE"
    }

    # Verify service is running
    Start-Sleep -Seconds 3
    $service = Get-Service -Name "{{ service_name }}" -ErrorAction SilentlyContinue
    if ($service.Status -ne 'Running') {
        throw "Service is not running. Status: $($service.Status)"
    }

    Write-Host "Windows service installed and started successfully"
  args:
    executable: powershell
  notify: restart tls-cert-monitor-windows-native

# Windows Defender Exclusion
- name: Check if Windows Defender exclusion should be added
  pause:
    prompt: >-
      Would you like to add a Windows Defender exclusion for tls-cert-monitor.exe?
      This can help prevent false positives and improve performance. (yes/no)
  register: defender_exclusion_prompt

- name: Add Windows Defender exclusion
  when: defender_exclusion_prompt.user_input | lower == 'yes'
  win_shell: |
    $exePath = "{{ install_dir_windows }}\\tls-cert-monitor.exe"

    # Check if Windows Defender is running
    $defenderService = Get-Service -Name "WinDefend" -ErrorAction SilentlyContinue
    if (-not $defenderService -or $defenderService.Status -ne 'Running') {
        Write-Host "Windows Defender is not running, skipping exclusion configuration"
        exit 0
    }

    # Check if exclusion already exists
    $existingExclusions = Get-MpPreference | Select-Object -ExpandProperty ExclusionPath
    if ($existingExclusions -contains $exePath) {
        Write-Host "Exclusion for $exePath already exists"
        exit 0
    }

    # Add the exclusion
    try {
        Add-MpPreference -ExclusionPath $exePath -ErrorAction Stop
        Write-Host "Successfully added Windows Defender exclusion for: $exePath"

        # Also add exclusion for the entire install directory
        $installDir = "{{ install_dir_windows }}"
        if ($existingExclusions -notcontains $installDir) {
            Add-MpPreference -ExclusionPath $installDir -ErrorAction SilentlyContinue
            Write-Host "Also added exclusion for installation directory: $installDir"
        }

        # Add exclusion for the config directory
        $configDir = "{{ config_dir_windows }}"
        if ($existingExclusions -notcontains $configDir) {
            Add-MpPreference -ExclusionPath $configDir -ErrorAction SilentlyContinue
            Write-Host "Also added exclusion for config directory: $configDir"
        }

        # Add exclusion for the log directory
        $logDir = "{{ log_dir_windows }}"
        if ($existingExclusions -notcontains $logDir) {
            Add-MpPreference -ExclusionPath $logDir -ErrorAction SilentlyContinue
            Write-Host "Also added exclusion for log directory: $logDir"
        }

        # Display current exclusions
        Write-Host "`nCurrent Windows Defender exclusions for tls-cert-monitor:"
        Get-MpPreference | Select-Object -ExpandProperty ExclusionPath |
            Where-Object { $_ -like "*tls-cert-monitor*" } |
            ForEach-Object { Write-Host "  - $_" }

    } catch {
        Write-Warning "Failed to add Windows Defender exclusion: $_"
        Write-Host "You may need to run this playbook with elevated privileges"
        exit 1
    }
  args:
    executable: powershell
  become: yes
  become_method: runas

- name: Configure Windows Firewall rule
  win_firewall_rule:
    name: "TLS Certificate Monitor"
    localport: "{{ service_port }}"
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: yes

- name: Verify service is running
  win_shell: |
    $service = Get-Service -Name "{{ service_name }}" -ErrorAction SilentlyContinue
    if (-not $service) {
        throw "Service '{{ service_name }}' not found"
    }

    if ($service.Status -ne 'Running') {
        throw "Service is not running. Status: $($service.Status)"
    }

    Write-Host "Service '{{ service_name }}' is running successfully"
    return $true
  args:
    executable: powershell
  register: service_status
  failed_when: service_status.rc != 0