---
# Windows installation tasks

- name: Create required directories
  win_file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ install_dir_windows }}"
    - "{{ config_dir_windows }}"
    - "{{ config_dir_windows }}\\certificates"
    - "{{ log_dir_windows }}"

- name: Download Windows binary
  win_get_url:
    url: "https://github.com/{{ github_repo }}/releases/download/{{ release_version }}/windows-{{ arch_name }}.tar.gz"
    dest: "{{ install_dir_windows }}\\tls-cert-monitor-{{ release_version }}.tar.gz"

- name: Extract Windows binary
  win_shell: |
    $tarPath = "{{ install_dir_windows }}\\tls-cert-monitor-{{ release_version }}.tar.gz"
    $extractPath = "{{ install_dir_windows }}"

    # Extract tar.gz
    tar -xzf $tarPath -C $extractPath

    # Verify executable exists
    if (-not (Test-Path "$extractPath\\tls-cert-monitor.exe")) {
        throw "Failed to extract tls-cert-monitor.exe"
    }

    # Remove archive
    Remove-Item $tarPath -Force
  args:
    executable: powershell

- name: Deploy configuration file
  win_template:
    src: config-windows.yaml.j2
    dest: "{{ config_dir_windows }}\\config.yaml"
    backup: yes

# Native Windows Service Installation (v1.2.0+)
- name: Install Windows service (native method)
  win_shell: |
    $exePath = "{{ install_dir_windows }}\\tls-cert-monitor.exe"
    $configPath = "{{ config_dir_windows }}\\config.yaml"

    # Check if service exists
    $service = Get-Service -Name "{{ service_name }}" -ErrorAction SilentlyContinue

    if ($service) {
        Write-Host "Stopping existing service..."
        Stop-Service -Name "{{ service_name }}" -Force -ErrorAction SilentlyContinue
        Start-Sleep -Seconds 2

        Write-Host "Uninstalling existing service..."
        & $exePath --service-uninstall
        Start-Sleep -Seconds 2
    }

    # Install the service with auto-start
    Write-Host "Installing native Windows service..."
    & $exePath --service-install --config $configPath

    if ($LASTEXITCODE -ne 0) {
        throw "Failed to install Windows service. Exit code: $LASTEXITCODE"
    }

    # Start the service
    Write-Host "Starting Windows service..."
    & $exePath --service-start

    if ($LASTEXITCODE -ne 0) {
        throw "Failed to start Windows service. Exit code: $LASTEXITCODE"
    }

    # Verify service is running
    Start-Sleep -Seconds 3
    $service = Get-Service -Name "{{ service_name }}" -ErrorAction SilentlyContinue
    if ($service.Status -ne 'Running') {
        throw "Service is not running. Status: $($service.Status)"
    }

    Write-Host "Windows service installed and started successfully"
  args:
    executable: powershell
  when: windows_service_method == "native"
  notify: restart tls-cert-monitor-windows-native

# NSSM Windows Service Installation (fallback/legacy)
- name: Download NSSM for service management
  win_get_url:
    url: "https://nssm.cc/release/nssm-2.24.zip"
    dest: "{{ install_dir_windows }}\\nssm.zip"
  when: windows_service_method == "nssm"

- name: Extract NSSM
  win_unzip:
    src: "{{ install_dir_windows }}\\nssm.zip"
    dest: "{{ install_dir_windows }}"
    creates: "{{ install_dir_windows }}\\nssm-2.24"
  when: windows_service_method == "nssm"

- name: Remove NSSM archive
  win_file:
    path: "{{ install_dir_windows }}\\nssm.zip"
    state: absent
  when: windows_service_method == "nssm"

- name: Install Windows service (NSSM method)
  win_shell: |
    $nssmPath = "{{ install_dir_windows }}\\nssm-2.24\\win64\\nssm.exe"
    $exePath = "{{ install_dir_windows }}\\tls-cert-monitor.exe"
    $configPath = "{{ config_dir_windows }}\\config.yaml"

    # Remove existing service if present
    & $nssmPath stop "{{ service_name }}" 2>$null
    & $nssmPath remove "{{ service_name }}" confirm 2>$null

    # Install service
    & $nssmPath install "{{ service_name }}" $exePath "--config" $configPath

    # Configure service
    & $nssmPath set "{{ service_name }}" DisplayName "TLS Certificate Monitor"
    & $nssmPath set "{{ service_name }}" Description "Monitor TLS certificates for expiration and security issues"
    & $nssmPath set "{{ service_name }}" Start SERVICE_AUTO_START
    & $nssmPath set "{{ service_name }}" AppStdout "{{ log_dir_windows }}\\service.log"
    & $nssmPath set "{{ service_name }}" AppStderr "{{ log_dir_windows }}\\service-error.log"
    & $nssmPath set "{{ service_name }}" AppRotateFiles 1
    & $nssmPath set "{{ service_name }}" AppRotateOnline 1
    & $nssmPath set "{{ service_name }}" AppRotateBytes 10485760

    # Start service
    & $nssmPath start "{{ service_name }}"
  args:
    executable: powershell
  when: windows_service_method == "nssm"
  notify: restart tls-cert-monitor-windows-nssm

- name: Configure Windows Firewall rule
  win_firewall_rule:
    name: "TLS Certificate Monitor"
    localport: "{{ service_port }}"
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: yes

- name: Verify service is running
  win_shell: |
    $service = Get-Service -Name "{{ service_name }}" -ErrorAction SilentlyContinue
    if (-not $service) {
        throw "Service '{{ service_name }}' not found"
    }

    if ($service.Status -ne 'Running') {
        throw "Service is not running. Status: $($service.Status)"
    }

    Write-Host "Service '{{ service_name }}' is running successfully"
    return $true
  args:
    executable: powershell
  register: service_status
  failed_when: service_status.rc != 0