---
# Main tasks for tls-cert-monitor role

# Variables are automatically loaded from group_vars/linux_servers.yml and group_vars/windows_servers.yml

- name: Set platform and architecture for binary download
  set_fact:
    platform_name: "{{ platform_map[ansible_system] | default(ansible_system | lower) }}"
    arch_name: "{{ arch_map[ansible_architecture] | default('amd64') }}"

- name: Include Linux vars
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/../group_vars/linux_servers.yml"
  when: "'linux_servers' in group_names"

- name: Include macOS vars
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/../group_vars/macos_servers.yml"
  when: "'macos_servers' in group_names"

- name: Include Windows vars
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/../group_vars/windows_servers.yml"
  when: "'windows_servers' in group_names"

- name: Debug platform and architecture detection
  debug:
    msg: "Detected OS: {{ ansible_system }}, Architecture: {{ ansible_architecture }}, Platform: {{ platform_name }}, Arch: {{ arch_name }}"

- name: Get latest release information
  include_tasks: get-release.yml

- name: Install on Linux
  include_tasks: install-linux.yml
  when: ansible_system == "Linux"

- name: Install on macOS
  include_tasks: install-macos.yml
  when: ansible_system == "Darwin"

- name: Install on Windows
  include_tasks: install-windows.yml
  when: ansible_os_family == "Windows"

- name: Setup TLS certificates
  include_tasks: setup-tls.yml
  when: enable_tls

- name: Verify installation
  include_tasks: verify.yml